@Library('mylib1') _

node{
    stage('Build'){
        checkout scm
        echo 'start build'
    }
    stage('Test'){
        checkout scm
        echo 'start test'
        res=readFile('tclist.txt')
        echo res
        withEnv(['PATH="C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\Scripts\\"']) {
         robot --pythonpath . tc
        }

    }
    stage('Deploy'){
        checkout scm
        echo 'start deploy'
    }
}