//@Library('mylib1') _
/*
node{
    stage('Build'){
        checkout scm
        echo 'start build'
    }
    stage('Test'){
        echo 'start test'
        res=readFile('tclist.txt')
        echo res

        //bat 'robot --pythonpath . --noncritical bugs tc'


    }
    stage('Deploy'){

        echo 'start deploy'
    }
}
*/




node{
    checkout scm
    import org.foo.Bar
    def bar=new Bar()
    bar.start()
}
